### ISSUE TITLE
Descobrir de onde vem usuarioWeb

### ISSUE THREAD

**Issue by bbviana** [matosmelo/git#6]
No codigo abaixo, quem coloca usuarioWeb na request?

```jsp
<c:if test="${usuarioWeb.logado}">
```
O vraptor poe sozinho?

**Comment by matosmelo** [comment]
O vraptor poe na hora que efetuo o login. A classe UsuarioWeb está anotada com o scopo @SessionScoped -  que é criada uma vez por sessão de usuario.
O vraptor colocou a instancia da componente como atributo da sessão, ou seja, para chamar preciso apenas escrever 
```jsp
 ${usuarioWeb}
```
sendo assim, da para acessar direto do jsp.

**Comment by bbviana** [comment]
Perfeito
